export const ADD_STAFFS = "ADD_STAFFS";
export const STAFFS_LOADING = "STAFFS_LOADING";
export const STAFFS_FAILED = "STAFFS_FAILED";
export const ADD_STAFF = "ADD_STAFF";
export const DELETE_STAFF = "DELETE_STAFF";
export const UPDATE_STAFF = "UPDATE_STAFF";

export const ADD_DEPT = "ADD_DEPT";
export const DEPT_LOADING = "DEPT_LOADING";
export const DEPT_FAILED = "DEPT_FAILED";

export const ADD_SALARY = "ADD_SALARY";
export const SALARY_LOADING = "SALARY_LOADING";
export const SALARY_FAILED = "SALARY_FAILED";

export const ADD_STAFFS_DEPT = "ADD_STAFFS_DEPT";
export const STAFFS_DEPT_LOADING = "STAFFS_DEPT_LOADING";
export const STAFFS_DEPTS_FAILED = "STAFFS_DEPT_FAILED";
